name: CI

on:
  push:
    branches: [enable-ci]
  pull_request:
    branches: [enable-ci]

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository ppa:alex-p/tesseract-ocr-devel &&
        sudo apt-get update &&
        sudo apt-get install tesseract-ocr && 
        ln -s /usr/lib/x86_64-linux-gnu/liblept.so.5 /usr/lib/x86_64-linux-gnu/libleptonica-1.82.0.so && 
        ln -s /usr/lib/x86_64-linux-gnu/libtesseract.so.5 /usr/lib/x86_64-linux-gnu/libtesseract50.so

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install tesseract
    
    - name: Install dependencies
      run: dotnet restore src/Tesseract.sln
      
    - name: Build
      run: dotnet build src/Tesseract.sln --no-restore
    
    - name: Test
      run: dotnet test src/Tesseract.sln --no-build --verbosity normal
