name: CI

on:
  push:
    branches: [enable-ci]
  pull_request:
    branches: [enable-ci]

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.1.x'

    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Install Ubuntu dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update &&
        sudo apt-get install -y tesseract-ocr libleptonica-dev && 
        ls -la /usr/local/lib && 
        ls -la /usr/lib/x86_64-linux-gnu

    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
        brew tap-new local/versions &&
        brew extract --version=4.1.1 tesseract local/versions &&
        brew install local/versions/tesseract@4.1.1 mono-libgdiplus
    
    - name: Install dependencies
      run: dotnet restore src/Tesseract.sln
      
    - name: Build
      run: dotnet build src/Tesseract.sln --no-restore
    
    - name: Test
      run: dotnet test src/Tesseract.sln --no-build --verbosity normal
